# -----------------------------------------------#
# CONFIGURATION FOR SYNTHETIC OCR DATA GENERATOR #
# -----------------------------------------------#

# PATHS
paths:
  corpus_dir: './corpus/'
  fonts_dir: './fonts/'
  backgrounds_dir: './backgrounds/'
  output_dir: './output/'

# DATASET SETTINGS
dataset:
  num_images: 100
  word_count_range: [1, 5]

# TEXT RENDERING
text:
  font_size_range: [38, 42]
  padding:
    top: 20
    right: 20
    bottom: 20
    left: 20
  color:
    enabled: true
    rgb_range: [0, 100] # each channel range (0 - 255)

# AUGMENTATIONS
augmentations:
  warp:
    enabled: true
    magnitude: 4
  tilt:
    enabled: true
    angle_range: [-10, 10]
  blur:
    enabled: true
    kernel_size_range: [1, 3] # must be odd integers
  brightness_contrast:
    enabled: true
    brightness_range: [-0.3, 0.3]
    contrast_range: [0.7, 1.3]
  noise:
    enabled: false
    type: 's&p' # salt-and-pepper
    amount_range: [0.01, 0.10]  # fraction of pixels to alter